spring:
  datasource:
    #    hikari:
    #      username: root
    #      driver-class-name: com.mysql.jdbc.Driver
    #      jdbc-url: jdbc:mysql:///db_ssh
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.55.100.241:3307/db_bookstore
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: none

  mail:
    default-encoding: utf-8
    port: 25
    host: smtp.qq.com
    username: 1050657124@qq.com
    password: ktmpwbsirrqjbdah

#security:
#  basic:
#    enabled: false
server:
  port: 8090
security:
  login:
    code-size: 6
    livetime: 60
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
